# Generated by Django 3.2.25 on 2024-06-26 01:53

from django.db import migrations, models
import django_file_tools.model_fields
import testapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Something',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_file_tools.model_fields.FileField(upload_to=testapp.models.name)),
            ],
        ),
    ]
